### ISSUE TITLE
Typo in marconi-sidechain error message

### ISSUE THREAD

**Issue by chrispalaskas** [input-output-hk/marconi#91]
When I run `marconi-sidechain --version` the error message returned is:
`GIHUB_SHA environment variable not set!` (without the T)
But the env var it is looking for is GITHUB_SHA
Also why would it expect the GITHUB_SHA to give the version? Doesn't the binary have an associated version?

**Comment by berewt** [comment]
The version stuff was awfully written, and is useless in its current version, we do apologise for it. We have a ticket for that internally but it is a low priority at the moment as there is no official release yet. (we really need to work on sharing here the issues we manage internally though).

**Comment by koslambrou** [comment]
Closing as fixed.
